slam_toolbox1:
  ros__parameters:

    # ---------------------------------------------------------------------
    # Plugin Configuration
    # ---------------------------------------------------------------------
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ---------------------------------------------------------------------
    # ROS Frames & Topics
    # ---------------------------------------------------------------------
    odom_frame: tb1/odom
    map_frame: tb1/map
    base_frame: tb1/base_link
    scan_topic: tb1/filtered_scan

    # ---------------------------------------------------------------------
    # Map Management
    # ---------------------------------------------------------------------
    use_map_saver: true
    mode: mapping
    publish_map_to_odom_transform: true
    

    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02
    map_update_interval: 0.2                  
    resolution: 0.05
    max_laser_range: 2.0
    use_invalid_range_as_free_space: true      
    use_non_hit_rays: true
    min_pass_through: 2                         
    occupancy_threshold: 0.1                    
    minimum_time_interval: 0.1                 
    transform_timeout: 0.5
    tf_buffer_duration: 60.0
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # ---------------------------------------------------------------------
    # Core SLAM Parameters
    # ---------------------------------------------------------------------
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.1               
    minimum_travel_heading: 0.1                
    scan_buffer_size: 20
    scan_buffer_maximum_scan_distance: 4.0      

    link_match_minimum_response_fine: 0.2       
    link_scan_maximum_distance: 2.0             
    loop_search_maximum_distance: 4.0          
    do_loop_closing: true
    loop_match_minimum_chain_size: 8            
    loop_match_maximum_variance_coarse: 2.0     
    loop_match_minimum_response_coarse: 0.3    
    loop_match_minimum_response_fine: 0.35      

    # ---------------------------------------------------------------------
    # Correlation Parameters - Local Matching
    # ---------------------------------------------------------------------
    correlation_search_space_dimension: 0.5     
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.05  

    # ---------------------------------------------------------------------
    # Correlation Parameters - Loop Closure
    # --------------------------------------------------------------------- 
    loop_search_space_dimension: 6.0            
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03     

    # ---------------------------------------------------------------------
    # Scan Matcher Settings
    # ---------------------------------------------------------------------
    distance_variance_penalty: 0.4              
    angle_variance_penalty: 0.8                 
    fine_search_angle_offset: 0.00174           
    coarse_search_angle_offset: 0.2618          
    coarse_angle_resolution: 0.01745            
    minimum_angle_penalty: 0.6
    minimum_distance_penalty: 0.4
    use_response_expansion: true

    # ---------------------------------------------------------------------


slam_toolbox2:
  ros__parameters:

    # ---------------------------------------------------------------------
    # Plugin Configuration
    # ---------------------------------------------------------------------
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ---------------------------------------------------------------------
    # ROS Frames & Topics
    # ---------------------------------------------------------------------
    odom_frame: tb2/odom
    map_frame: tb2/map
    base_frame: tb2/base_link
    scan_topic: tb2/filtered_scan

    # ---------------------------------------------------------------------
    # Map Management
    # ---------------------------------------------------------------------
    use_map_saver: true
    mode: mapping
    publish_map_to_odom_transform: true
    

    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02
    map_update_interval: 0.2                  
    resolution: 0.05
    max_laser_range: 2.0
    use_invalid_range_as_free_space: true      
    use_non_hit_rays: true
    min_pass_through: 2                         
    occupancy_threshold: 0.1                    
    minimum_time_interval: 0.1                 
    transform_timeout: 0.5
    tf_buffer_duration: 60.0
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # ---------------------------------------------------------------------
    # Core SLAM Parameters
    # ---------------------------------------------------------------------
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.1               
    minimum_travel_heading: 0.1                
    scan_buffer_size: 20
    scan_buffer_maximum_scan_distance: 4.0      

    link_match_minimum_response_fine: 0.2       
    link_scan_maximum_distance: 2.0             
    loop_search_maximum_distance: 4.0          
    do_loop_closing: true
    loop_match_minimum_chain_size: 8            
    loop_match_maximum_variance_coarse: 2.0     
    loop_match_minimum_response_coarse: 0.3    
    loop_match_minimum_response_fine: 0.35      

    # ---------------------------------------------------------------------
    # Correlation Parameters - Local Matching
    # ---------------------------------------------------------------------
    correlation_search_space_dimension: 0.5     
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.05  

    # ---------------------------------------------------------------------
    # Correlation Parameters - Loop Closure
    # --------------------------------------------------------------------- 
    loop_search_space_dimension: 6.0            
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03     

    # ---------------------------------------------------------------------
    # Scan Matcher Settings
    # ---------------------------------------------------------------------
    distance_variance_penalty: 0.4              
    angle_variance_penalty: 0.8                 
    fine_search_angle_offset: 0.00174           
    coarse_search_angle_offset: 0.2618          
    coarse_angle_resolution: 0.01745            
    minimum_angle_penalty: 0.6
    minimum_distance_penalty: 0.4
    use_response_expansion: true

    # ---------------------------------------------------------------------


slam_toolbox3:
  ros__parameters:

    # ---------------------------------------------------------------------
    # Plugin Configuration
    # ---------------------------------------------------------------------
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ---------------------------------------------------------------------
    # ROS Frames & Topics
    # ---------------------------------------------------------------------
    odom_frame: tb3/odom
    map_frame: tb3/map
    base_frame: tb3/base_link
    scan_topic: tb3/filtered_scan

    # ---------------------------------------------------------------------
    # Map Management
    # ---------------------------------------------------------------------
    use_map_saver: true
    mode: mapping
    publish_map_to_odom_transform: true
    

    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02
    map_update_interval: 0.2                  
    resolution: 0.05
    max_laser_range: 2.0
    use_invalid_range_as_free_space: true      
    use_non_hit_rays: true
    min_pass_through: 2                         
    occupancy_threshold: 0.1                    
    minimum_time_interval: 0.1                 
    transform_timeout: 0.5
    tf_buffer_duration: 60.0
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # ---------------------------------------------------------------------
    # Core SLAM Parameters
    # ---------------------------------------------------------------------
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.1               
    minimum_travel_heading: 0.1                
    scan_buffer_size: 20
    scan_buffer_maximum_scan_distance: 4.0      

    link_match_minimum_response_fine: 0.2       
    link_scan_maximum_distance: 2.0             
    loop_search_maximum_distance: 4.0          
    do_loop_closing: true
    loop_match_minimum_chain_size: 8            
    loop_match_maximum_variance_coarse: 2.0     
    loop_match_minimum_response_coarse: 0.3    
    loop_match_minimum_response_fine: 0.35      

    # ---------------------------------------------------------------------
    # Correlation Parameters - Local Matching
    # ---------------------------------------------------------------------
    correlation_search_space_dimension: 0.5     
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.05  

    # ---------------------------------------------------------------------
    # Correlation Parameters - Loop Closure
    # --------------------------------------------------------------------- 
    loop_search_space_dimension: 6.0            
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03     

    # ---------------------------------------------------------------------
    # Scan Matcher Settings
    # ---------------------------------------------------------------------
    distance_variance_penalty: 0.4              
    angle_variance_penalty: 0.8                 
    fine_search_angle_offset: 0.00174           
    coarse_search_angle_offset: 0.2618          
    coarse_angle_resolution: 0.01745            
    minimum_angle_penalty: 0.6
    minimum_distance_penalty: 0.4
    use_response_expansion: true

    # ---------------------------------------------------------------------


slam_toolbox4:
  ros__parameters:

    # ---------------------------------------------------------------------
    # Plugin Configuration
    # ---------------------------------------------------------------------
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ---------------------------------------------------------------------
    # ROS Frames & Topics
    # ---------------------------------------------------------------------
    odom_frame: tb4/odom
    map_frame: tb4/map
    base_frame: tb4/base_link
    scan_topic: tb4/filtered_scan

    # ---------------------------------------------------------------------
    # Map Management
    # ---------------------------------------------------------------------
    use_map_saver: true
    mode: mapping
    publish_map_to_odom_transform: true
    

    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02
    map_update_interval: 0.2                  
    resolution: 0.05
    max_laser_range: 2.0
    use_invalid_range_as_free_space: true      
    use_non_hit_rays: true
    min_pass_through: 2                         
    occupancy_threshold: 0.1                    
    minimum_time_interval: 0.1                 
    transform_timeout: 0.5
    tf_buffer_duration: 60.0
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # ---------------------------------------------------------------------
    # Core SLAM Parameters
    # ---------------------------------------------------------------------
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.1               
    minimum_travel_heading: 0.1                
    scan_buffer_size: 20
    scan_buffer_maximum_scan_distance: 4.0      

    link_match_minimum_response_fine: 0.2       
    link_scan_maximum_distance: 2.0             
    loop_search_maximum_distance: 4.0          
    do_loop_closing: true
    loop_match_minimum_chain_size: 8            
    loop_match_maximum_variance_coarse: 2.0     
    loop_match_minimum_response_coarse: 0.3    
    loop_match_minimum_response_fine: 0.35      

    # ---------------------------------------------------------------------
    # Correlation Parameters - Local Matching
    # ---------------------------------------------------------------------
    correlation_search_space_dimension: 0.5     
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.05  

    # ---------------------------------------------------------------------
    # Correlation Parameters - Loop Closure
    # --------------------------------------------------------------------- 
    loop_search_space_dimension: 6.0            
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03     

    # ---------------------------------------------------------------------
    # Scan Matcher Settings
    # ---------------------------------------------------------------------
    distance_variance_penalty: 0.4              
    angle_variance_penalty: 0.8                 
    fine_search_angle_offset: 0.00174           
    coarse_search_angle_offset: 0.2618          
    coarse_angle_resolution: 0.01745            
    minimum_angle_penalty: 0.6
    minimum_distance_penalty: 0.4
    use_response_expansion: true