FROM ros:jazzy

RUN apt-get update && apt-get install -y --no-install-recommends \
    # GUI Libraries
    x11-apps \
    # Base and utility ROS packages
    ros-jazzy-rqt-graph \
    ros-jazzy-rqt-console \
    wget \
    ros-jazzy-urdf-tutorial \
    liburdfdom-tools \
    # Gazebo
    ros-jazzy-ros-gz \
    # Navigation & SLAM
    ros-jazzy-navigation2 \
    ros-jazzy-nav2-bringup \
    ros-jazzy-slam-toolbox \
    # Python and build dependencies
    python3-colcon-common-extensions \
    ros-jazzy-test-msgs \
    python3-numpy \
    python3-sklearn \
    ros-jazzy-laser-filters \
    # TurtleBot3 packages
    ros-jazzy-turtlebot3 \
    ros-jazzy-image-geometry \
    ros-jazzy-turtlebot3-simulations \
    && rm -rf /var/lib/apt/lists/*


# Create workspace
WORKDIR /root/ros_workspace

# Compile the workspace to make the new package available.
# It is necessary to source the ROS environment before compiling.
RUN . /opt/ros/jazzy/setup.sh && colcon build --symlink-install
